platform :ios, ’8.0’
use_frameworks!

target 'FirstJapaneseLife' do
    pod 'SnapKit'
    pod 'AYNavigationBar'
    pod 'Agrume'
    pod 'HandyJSON', '~> 4.0.0-beta.1'
    pod 'SDCycleScrollView'
end
